### ISSUE TITLE
not generating creds  

### ISSUE THREAD

**Issue by r2690698** [ddimitrioglo/aws-saml#12]
Hello, having an issue that when running the aws-saml configure and fill in the info i am getting the ✅ Done! but when looking in ~/.aws/credentials  i am not seeing anything in ~/.aws/credentials 

my setup is the bellow using AzureAD SSO. 

{
  "profile": "demo",
  "username": "steven.cuthill@XXXXXXX",
  "password": "XXXXXXXX",
  "directoryDomain": "https://myapps.microsoft.com/signin/XXXX/XXXXX",
  "aliases": {}
}

**Comment by ddimitrioglo** [comment]
Hi @r2690698,

`configure` command just saves your data in `aws-saml` config and does not change anything in `~/.aws/credentials`
In order to get temporarily credentials (and see them in `~/.aws/credentials`) you have to run `aws-saml login`, have you done this?

**Comment by ddimitrioglo** [comment]
BTW 
* `password` should not be plain password (you have to encrypt it bu running `aws-saml password`)
* `directoryDomain` should be domain only ex: `"https://directory.mitocgroup.com"`

**Comment by ddimitrioglo** [comment]
Hi @r2690698,
Have you succeeded to login?

**Comment by ddimitrioglo** [comment]
closing as irrelevant
