### ISSUE TITLE
directoryDomain - Formats / Examples

### ISSUE THREAD

**Issue by miztiik** [ddimitrioglo/aws-saml#14]
Not exactly an issue, Trying to setup my creds for SAML. But not sure what is the exact format.

FQDN? 
or 
just the corp-directory-name.com?

Is it possible for you to provide some default examples for say:Okta, Azure AD etc.,

**Comment by ddimitrioglo** [comment]
Hi @miztiik,
Sorry for the late answer. I build this tool to simplify my day-by-day login to AWS's SSO Solution, so didn't have a chance to test in Azure on something like this.

Generally, it should look like `"directoryDomain": "https://directory.mycorp.com"` but you fail to login, please provide me the error log and I will happily investigate it and try to help you!

P.S. [Here](https://github.com/ddimitrioglo/aws-saml#configuration) you can take a look to existing example.

**Comment by miztiik** [comment]
Thanks for response, Lets close this, At this moment, this tool _may_ not able able to satisfy my needs and have removed my setup and unable to provide any more logs.

Appreciate your efforts though.

**Comment by ddimitrioglo** [comment]
@miztiik thank you too!
BTW, if you have some ideas how to improve this tool - please open an issue with `enhancement` tag, we will try to handle in next releases.
