### ISSUE TITLE
Alias option doesnt work , throws error:040A1079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error

### ISSUE THREAD

**Issue by aashrit93** [ddimitrioglo/aws-saml#17]
Hi ddimitrioglo,
aws-saml version 1.1.2

as mentioned in the documentation I created a config.json file with the aliases section like below :
{
      "profile": "saml",                    
      "username": "****@**.com",             
      "password": "*****",
      "directoryDomain": "https://****/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices",
      "aliases": {    
          "ACCOUNTID":"nonprod"
        }
    }
I ran
1. aws-saml login --alias nonprod and got error:040A1079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error

same issue when i run aws-saml login --alias
Thanks in advance!

**Comment by ddimitrioglo** [comment]
Hi @aashrit93 ,

To fix the issue faster, could you please answer several questions?

* Is usual (interactive) flow working? (`aws-saml login`)
* Are you trying to configure password via CLI or adding manually to the `~/.aws-saml/config.json`?
* Is your password value in `~/.aws-saml/config.json` a valid base64 string?

Thank you.

**Comment by aashrit93** [comment]
Hi Dmirtri,

Thank you so much for your prompt reply. I realized I was storing the
password as a regular UTF-8 string in the ~/.aws-saml/config.json file.
Making the string base64 worked. I really appreciate the effort you took to
build this package, it makes life easier for me . Cheers :)

Regards,
Aashrit

**Comment by ddimitrioglo** [comment]
Hi @aashrit93 !

Glad to hear that you could configure and make it working!
Thank you for the feedback 😉
