### ISSUE TITLE
`Cannot find AWS CLI profile` error during login 

### ISSUE THREAD

**Issue by avozicov** [ddimitrioglo/aws-saml#3]
I have faced an issue when tried to login with the tool right after configuring it which would be great to fix ;)

Here is the use case: 
- If you try to run `aws-saml login` with the missing `saml` profile in you `~/.aws/credentials` you will face the following issue 
<img width="387" alt="screen shot 2018-04-12 at 18 44 42" src="https://user-images.githubusercontent.com/12330493/38688880-dcfe5902-3e82-11e8-814d-67bfb95798d0.png">

I have resolved it by adding `saml` profile in `~/.aws/credentials` file and then everything works as expexted

**Comment by ddimitrioglo** [comment]
@avozicov will investigate this issue and come back with updates

**Comment by ddimitrioglo** [comment]
@avozicov fixed in version `v1.0.0`

**Comment by avozicov** [comment]
Confirm applied fix,  ;)
Thank you @ddimitrioglo !
