### ISSUE TITLE
After running aws-saml login everything except saml profile in ~/.aws/credentials was lost

### ISSUE THREAD

**Issue by eistrati** [ddimitrioglo/aws-saml#5]
I created ~/.aws/credentials, but after running aws-saml login everything was lost. Looks like this tool overwrites everything when generated saml profile (all other profiles are deleted).

**Comment by ddimitrioglo** [comment]
confirm this behavior, will fix this ASAP

**Comment by ddimitrioglo** [comment]
@eistrati fixed in `aws-saml@1.0.1`
