### ISSUE TITLE
Authentication parameters should be configurable

### ISSUE THREAD

**Issue by marcoreni** [ddimitrioglo/aws-saml#7]
The `_login` function inside `saml.js` performs the actual post request but sets a `CORP` domain ( https://github.com/ddimitrioglo/aws-saml/blob/master/lib/saml.js#L61 ) . This is incompatible with setups where the domain is different.

Perhaps this value can be parametrized via configuration (with a default, to guarantee backwards compatibility)?

**Comment by ddimitrioglo** [comment]
Hi @marcoreni, thanks for your feedback.
That value could be parametrized via configuration, but in order to do this - I would want to see real use case when current implementation has to be improved.
Can you provide a proper example?

**Comment by marcoreni** [comment]
Hello @ddimitrioglo .

My company has a "companyname.com" domain. Using the standard web authentication for SAML, I would use either `marcoreni@companyname.com` or `companyname.com\marcoreni` as username.

Using this library authentication would fail because the script would insert `CORP` before the username, so my POSTed username would be `CORP\companyname.com\marcoreni` or `CORP\marcoreni@companyname.com`.

By providing the domain as a configuration value we would be able to configure the domain according to our specific configuration, or (by leaving it empty), allow the users to provide the full username as they're already used to do.

Does this help you?

**Comment by ddimitrioglo** [comment]
The `CORP` prefix allows you do not pass domain part of email, so in your case instead of using `marcoreni@companyname.com` just pass `marcoreni`.

Generally your proposal makes sense, but I've tried to be consistent with the UI, which is looking like this:
![image](https://user-images.githubusercontent.com/9005667/39861508-7fa60020-5449-11e8-9d78-548d62d77f86.png)

Please let me know if passing `marcoreni` as username will cover your use-case.

**Comment by marcoreni** [comment]
Yeah, that would do it. 

In our UI we have to provide the `@domain` or the `domain\` part ourselves, but I think it wouldn't be hard to explain the users that in this particular scenario they should simply use the username :)

**Comment by ddimitrioglo** [comment]
Implemented in `aws-saml@1.0.2`
