### ISSUE TITLE
Some characters disappear after running aws-saml login

### ISSUE THREAD

**Issue by eistrati** [ddimitrioglo/aws-saml#8]
Here below is my ~/.aws/credentials before running `aws-saml login`:
```
[default]
aws_access_key_id=AKIAG***
aws_secret_access_key=M0mqn***
```

Here below is my ~/.aws/credentials after running `aws-saml login`:
```
[default]
aws_access_key_id = KIAG***
aws_secret_access_key = 0mqn***
```

Please fix it ;)

**Comment by ddimitrioglo** [comment]
@eistrati which Node.js version are you using?

**Comment by eistrati** [comment]
```
$ node -v
v6.11.0
```

**Comment by ddimitrioglo** [comment]
@eistrati I confirm your issue.

**Steps to reproduce**:
* I've added some fake credentials the same way you did it:

![image](https://user-images.githubusercontent.com/9005667/48315425-b8291280-e5de-11e8-8aff-4f93db0a5acb.png)

* And after `aws-saml login` I've received:

![image](https://user-images.githubusercontent.com/9005667/48315462-31286a00-e5df-11e8-84e9-7d1b57e00eda.png)

Starting investigating your use-case and come with updates ;)

**Comment by ddimitrioglo** [comment]
@eistrati in **v1.1.0** this unpleasant issue was fixed!
