### ISSUE TITLE
Add options for each requested variable.

### ISSUE THREAD

**Issue by gcaraman-zz** [ddimitrioglo/aws-saml#9]
e.g.: -u (--user), -p (--password), -a (--account)

**Comment by ddimitrioglo** [comment]
Hi @gcaraman, 

This auto-login feature was implemented in following way:

* Add an alias (ex. `myacc`) for required AWS account, `aws-saml alias --account 888999888999`
* Configure a password (will be encrypted), `aws-saml password`
* Use auto-login `aws-saml login --alias myacc` (this will use 888999888999 AWS account and configured password)
